export interface SupervisorReportStudent {
  name: string;
  email: string;
  assignedDate: string;
  statement: string;
}

export interface SupervisorReportItem {
  id: string;
  name: string;
  email: string;
  areasOfInterest: string[];
  studentCount: number;
  students: SupervisorReportStudent[];
}

export async function generateAdminPDFReport(
  rawReport: SupervisorReportItem[],
  generatedBy: string = "Administrator"
) {
  const report = [...rawReport].sort((a, b) => b.studentCount - a.studentCount);

  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginL = 50;
  const marginR = pageW - 50;

  // Computer local time down to the second
  const localTimestamp = new Date().toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
  const totalStudents = report.reduce((acc, sup) => acc + sup.studentCount, 0);

  if (report.length === 0) {
    doc.setFontSize(12);
    doc.text("No supervisors found in database.", marginL, 100);
  } else {
    // --- COVER PAGE (Executive Summary, Workload Chart & Directory Table) ---
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text("STUDENT SUPERVISION APPLICATION — MASTER REPORT", marginL, 45);

    doc.setDrawColor(0);
    doc.setLineWidth(1.5);
    doc.line(marginL, 52, marginR, 52);

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE SUMMARY & SUPERVISOR DIRECTORY", marginL, 75);

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80);
    doc.text(
      `Generated by: ${generatedBy}  |  Generated on: ${localTimestamp}  |  Total Supervisors: ${report.length}  |  Active Pairings: ${totalStudents}`,
      marginL,
      90
    );

    doc.setLineWidth(0.5);
    doc.setDrawColor(180);
    doc.line(marginL, 98, marginR, 98);

    // Vector Workload Bar Chart on Cover Page
    const maxCount = Math.max(...report.map((s) => s.studentCount), 1);
    const chartStartY = 114;
    doc.setFontSize(9.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("SUPERVISOR WORKLOAD DISTRIBUTION CHART", marginL, chartStartY);

    let currentY = chartStartY + 14;
    const barMaxW = 270;

    report.forEach((sup) => {
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40);
      const truncatedName = sup.name.length > 18 ? sup.name.slice(0, 16) + "…" : sup.name;
      doc.text(truncatedName, marginL, currentY + 9);

      const barX = marginL + 110;
      const barW = Math.max((sup.studentCount / maxCount) * barMaxW, sup.studentCount > 0 ? 6 : 0);

      // Red (>=5), Orange (>=3), Green (<3)
      if (sup.studentCount >= 5) {
        doc.setFillColor(239, 68, 68);
      } else if (sup.studentCount >= 3) {
        doc.setFillColor(249, 115, 22);
      } else {
        doc.setFillColor(16, 185, 129);
      }

      if (barW > 0) {
        doc.roundedRect(barX, currentY + 1, barW, 9, 2, 2, "F");
      }

      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 41, 59);
      doc.text(String(sup.studentCount), barX + barW + 6, currentY + 9);

      currentY += 15;
    });

    const summaryTableStartY = currentY + 12;

    // Master Summary Directory Table
    autoTable(doc, {
      startY: summaryTableStartY,
      margin: { left: marginL, right: 50 },
      head: [["#", "Supervisor Name", "Email Address", "Areas of Interest", "Students"]],
      body: report.map((sup, i) => [
        String(i + 1),
        sup.name,
        sup.email,
        sup.areasOfInterest.length > 0 ? sup.areasOfInterest.join(", ") : "General",
        String(sup.studentCount),
      ]),
      headStyles: {
        fillColor: [30, 41, 59] as any,
        textColor: 255,
        fontStyle: "bold",
        fontSize: 8.5,
      },
      bodyStyles: {
        textColor: 0,
        fontSize: 8,
        cellPadding: 5,
      },
      alternateRowStyles: {
        fillColor: [245, 247, 250] as any,
      },
      columnStyles: {
        0: { cellWidth: 22, halign: "center" },
        1: { cellWidth: 110 },
        2: { cellWidth: 135 },
        3: { cellWidth: "auto" },
        4: { cellWidth: 50, halign: "center" },
      },
    });

    // --- INDIVIDUAL SUPERVISOR BREAKDOWN PAGES ---
    report.forEach((sup, supIdx) => {
      doc.addPage();

      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0);
      doc.text("STUDENT SUPERVISION APPLICATION — MASTER REPORT", marginL, 45);

      doc.setDrawColor(0);
      doc.setLineWidth(1.5);
      doc.line(marginL, 52, marginR, 52);

      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(`Supervisor Breakdown (${supIdx + 1} of ${report.length}): ${sup.name}`, marginL, 76);

      doc.setLineWidth(0.5);
      doc.line(marginL, 84, marginR, 84);

      const metaStartY = 100;
      const lineH = 16;
      const interests = sup.areasOfInterest.length > 0 ? sup.areasOfInterest.join(", ") : "General Supervision";

      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("Supervisor Name:", marginL, metaStartY);
      doc.text("Email Address:", marginL, metaStartY + lineH);
      doc.text("Areas of Interest:", marginL, metaStartY + lineH * 2);
      doc.text("Date Generated:", marginL, metaStartY + lineH * 3);
      doc.text("Allocated Students:", marginL, metaStartY + lineH * 4);

      doc.setFont("helvetica", "normal");
      doc.text(sup.name, marginL + 115, metaStartY);
      doc.text(sup.email, marginL + 115, metaStartY + lineH);

      const interestLines = doc.splitTextToSize(interests, marginR - marginL - 120);
      doc.text(interestLines, marginL + 115, metaStartY + lineH * 2);
      const interestHeight = (interestLines.length - 1) * 12;

      doc.text(localTimestamp, marginL + 115, metaStartY + lineH * 3 + interestHeight);
      doc.text(String(sup.studentCount), marginL + 115, metaStartY + lineH * 4 + interestHeight);

      const tableStartY = metaStartY + lineH * 5 + interestHeight + 10;

      doc.setLineWidth(0.5);
      doc.line(marginL, tableStartY - 6, marginR, tableStartY - 6);

      if (sup.students.length === 0) {
        doc.setFontSize(9);
        doc.setFont("helvetica", "italic");
        doc.text("No allocated students for this supervisor.", marginL, tableStartY + 15);
      } else {
        autoTable(doc, {
          startY: tableStartY,
          margin: { left: marginL, right: 50 },
          head: [["#", "Student Name", "Student Email", "Assigned", "Statement of Interest"]],
          body: sup.students.map((st, i) => [
            String(i + 1),
            st.name,
            st.email,
            st.assignedDate,
            st.statement || "(no statement provided)",
          ]),
          headStyles: {
            fillColor: [30, 41, 59] as any,
            textColor: 255,
            fontStyle: "bold",
            fontSize: 8.5,
          },
          bodyStyles: {
            textColor: 0,
            fontSize: 8.5,
            cellPadding: 5,
          },
          alternateRowStyles: {
            fillColor: [245, 247, 250] as any,
          },
          columnStyles: {
            0: { cellWidth: 22, halign: "center" },
            1: { cellWidth: 95 },
            2: { cellWidth: 125 },
            3: { cellWidth: 65, halign: "center" },
            4: { cellWidth: "auto" },
          },
        });
      }
    });
  }

  // Page footer pass
  const totalPages = doc.getNumberOfPages();
  for (let pg = 1; pg <= totalPages; pg++) {
    doc.setPage(pg);
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(marginL, pageH - 38, marginR, pageH - 38);

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80);

    doc.text("Student Supervision Application — Master Report", marginL, pageH - 24);
    doc.text(`Page ${pg} of ${totalPages}`, pageW / 2, pageH - 24, { align: "center" });

    doc.setTextColor(0);
  }

  doc.save(`admin-supervisors-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
